apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Chart.Version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Chart.Version | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      containers:
        - name: vote
          image: {{ .Values.images.vote }}
          imagePullPolicy: {{default "Always" .Values.images.pullPolicy}}
          ports:
            - containerPort: 80
              name: http
          env:
          - name: REDIS_HOST
            value: {{ .Values.redis.host | default (printf "%s-redis" ( .Release.Name )) | quote }}
