apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Chart.Version | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Chart.Version | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      containers:
        - name: {{ template "fullname" . }}
          image: {{ .Values.images.worker }}
          imagePullPolicy: {{default "Always" .Values.images.pullPolicy}}
          env:
          - name: POSTGRES_SERVER
            value: {{ .Values.postgresql.server | default (printf "%s-postgresql" ( .Release.Name )) | quote }}
          - name: POSTGRES_USERNAME
            value: {{ .Values.postgresql.username | default "postgres" | quote }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "postgresql-{{ .Release.Name }}"
                key: password
          - name: REDIS_HOST
            value: {{ .Values.redis.host | default (printf "%s-redis" ( .Release.Name )) | quote }}
